# TODO: Test with different py versions using sub workflows

# NOTE: The following variables are required for this pipeline to work
# GIT_COMMIT_USER: The username of the gitlab user that will be used to push tags
# GIT_COMMIT_EMAIL: The email of the gitlab user that will be used to push tags
# PYPI_TOKEN: The token to use to publish to pypi

image: python:{{ cookiecutter.python_version }}

stages:
  - lint
  - test
  - bump
  - version
  - build
  - release
  - deploy


# Pipeline rules
workflow:
  rules:
      # Prevent running a push pipeline for a release commit that's not a tag
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\):.*/ && $CI_COMMIT_TAG == null
      when: never
      # If a push to branch with open merge request then ignore
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
      # If source is push and no open merge request then run
    - if: $CI_COMMIT_BRANCH
      # Run tag pipelines
    - if: $CI_COMMIT_TAG


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# Default cache values
default:
  cache: &global_cache
    key: 'main'
    paths:
      - .cache/pypoetry
      - .cache/pip
      - .venv/
    policy: pull-push


# Anchor to use pull only cache
.use_cached_venv: &use_cached_venv
  before_script:
    - source .venv/bin/activate
  cache:
    <<: *global_cache
    policy: pull


.only_tag: &only_tag
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never


.no_tag: &no_tag
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success


.only_protected: &only_protected
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: on_success
    - when: never


# Anchor for docker jobs
.docker-job:
  image: docker:latest
  services:
    - docker:dind
  # Deactivate cache for docker jobs
  cache: []

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


# Setup job to install dependencies
build-env:
  stage: .pre
  script:
    - python -m venv .venv/
    - source .venv/bin/activate
    - pip install -U pip
    - pip install poetry
    - poetry install
    # Install go-task
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b .
  rules:
      # If project dependencies were changed then run
    - changes:
      - pyproject.toml
      - {{ cookiecutter.project_slug }}/
      when: always
      # If .venv exists then skip
    - exists:       
      - .venv/
      when: never
    # Default to manual, but continue
    # pipeline if not run
    - when: manual
      allow_failure: true


lint-commit:
  <<: *use_cached_venv
  <<: *no_tag
  stage: lint
  script:
    - |
      # Get the commit message of the last commit
      commit_message=$(git log -1 --pretty=format:%s)

      # If the commit message starts with "Merge branch", it is a merge commit, so skip the linting.
      if [[ $commit_message == 'Merge branch'* ]]; then
        echo "Merge commit detected, skipping lint."
        exit 0
      fi

      pip install gitlint
      # Ensure the commit message is valid
      # We should always pass this as long as the pusher has the pre-commit hooks installed
      # but just as a sanity check we'll run it here
      git log -1 --pretty=%B | gitlint


lint-code:
  <<: *use_cached_venv
  <<: *no_tag
  stage: lint
  script:
      # Ensure the code is formatted correctly
    - ./task lint


unit-tests:
  <<: *use_cached_venv
  <<: *no_tag
  stage: test
  script:
    - ./task unit-tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
    paths:
      - coverage-report/


bump-version:
  <<: *only_protected
  variables:
    REPO_URL: "https://release-token:${RELEASE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  stage: bump
  before_script:
    - pip install -U commitizen
      # Set git info
    - git config --global user.email "$GIT_COMMIT_EMAIL"
    - git config --global user.name "$GIT_COMMIT_USER"
      # NOTE: Must be set to CLONE strategy in gitlab CI otherwise there will be
      # excess commits and tags from a dirty cache
    - git checkout $CI_COMMIT_BRANCH
    - git pull $REPO_URL $CI_COMMIT_BRANCH
      # Explicitly checkout branch since gitlab CI detaches
  script:
    # Bump the version
    - export CZ_BUMP_OUTPUT=$(cz bump --yes 2>&1)
    - export CZ_BUMP_EXIT_CODE=$?
    - echo $CZ_BUMP_OUTPUT
    - echo $CZ_BUMP_EXIT_CODE
    # Push new tag to trigger release workflow if bumped
    - |
      if [[ $CZ_BUMP_OUTPUT == *"[NO_COMMITS_TO_BUMP]"* ]]; then
        echo "Version unchanged."
      else
        echo "Version changed."
        git push $REPO_URL $CI_COMMIT_BRANCH --tags
      fi


get-version:
  <<: *use_cached_venv
  <<: *only_tag
  stage: version
  script:
    # Create release.env
    - echo "VERSION=$(poetry version --short)" >> release.env
    # Ensure the file is formatted correctly
    - cat release.env
  artifacts:
    reports:
      dotenv: release.env


build-docs:
  <<: *use_cached_venv
  <<: *only_tag
  stage: build
  script:
    - ./task build-docs
  artifacts:
    paths:
      - site/
    expire_in: 1 week


build-wheel:
  <<: *use_cached_venv
  <<: *only_tag
  stage: build
  script:
    # Build the wheel
    - ./task build-whl
  artifacts:
    name: dist
    paths:
      - dist/


make-release:
  <<: *use_cached_venv
  <<: *only_tag
  stage: release
  needs:
    - job: get-version
      artifacts: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Building release $VERSION"
  release:
    name: Release $VERSION
    tag_name: $VERSION
    description: $CHANGELOG


publish-wheel:
  <<: *use_cached_venv
  <<: *only_tag
  stage: release
  script: |
      # Publish the built wheel to the registry
      poetry config pypi-token.pypi $PYPI_TOKEN
      poetry publish
