site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_description }}
site_author: {{ cookiecutter.project_author }}
copyright: {{ cookiecutter.project_author }}
site_url: {{ cookiecutter.project_url }}
repo_url: {{ cookiecutter.repository }}
repo_name: {{ cookiecutter.project_slug }}

nav:
  - Overview: index.md

extra_css:
  - assets/css/theme.css

theme: 
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - toc.integrate
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  palette:
    scheme: slate
    primary: custom
    accent: custom

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.caret
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true